### ISSUE TITLE
Negative sampling applied to validation set in RecSys 22 tutorial

### ISSUE THREAD

**Issue by zhiruiwang** [NVIDIA-Merlin/publications#13]
Hi Merlin team,

I noticed that in the most recent version of [RecSys 22 tutorial notebook 4](https://github.com/NVIDIA-Merlin/publications/blob/main/tutorials/RecSys22tutorial/04_Building_Multi_Stage_RecSys.ipynb) DLRM modeling part, negative sampling is applied to the validation set:
```
valid_dataset = BatchedDataset(valid, shuffle=False, batch_size = batch_size)
valid_dataset = valid_dataset.map(add_negatives)
metrics = model.evaluate(valid_dataset, return_dict=True)
metrics
```
Which yields validation AUC of 0.83

But in an earlier version of the same notebook, there was an additional line of code evaluating the model on the raw validation set without negative samping:
```
model.evaluate(valid_raw, return_dict=True, batch_size = 2048)
```
This outcome only yields AUC of 0.57

I'm wondering if it is a common practice to apply negative sampling to validation set as well? If not, should we evaluate on the raw validation set instead?

Thanks!

**Comment by zhiruiwang** [comment]
Thanks for updating the notebook to explain this better! 

From [RecSys 22 tutorial notebook 4](https://github.com/NVIDIA-Merlin/publications/blob/main/tutorials/RecSys22tutorial/04-Building-multi-stage-RecSys.ipynb)
```
We evaluate the model using augmented, negative-sampling applied validation set assuming that we do not have explicit negatives in our dataset, which is the assumption in this exercise.
```
This makes total sense. Since the explicit negative in the original dataset is session-based, it doesn't make sense to train on negative-sampled data and validate on the original data, the training and validation should apply the same strategy.

We can close the ticket.

**Comment by PaulSteffen-betclic** [comment]
Hello,

I'm a new user of the framework and I found this example of negative sampling for ranking models:
<img width="992" alt="image" src="https://github.com/NVIDIA-Merlin/publications/assets/46781050/0a4b48dc-565b-4d6d-84a8-7461861f4a75">

But the framework seems to change, and it's no longer available.
What is the new way to use negative sampling in ranking models ?
